# Generated by Django 2.1.2 on 2018-10-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='label',
            new_name='channel_id',
        ),
    ]
