# Generated by Django 2.1.2 on 2018-10-18 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20181018_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='users',
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
