# Generated by Django 2.1.2 on 2018-10-18 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20181018_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
