# Generated by Django 3.0 on 2019-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20181103_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('channel_name', 'channel_url')},
        ),
    ]
